[project]
name = "tl-xlwings-automations"
version = "0.1.0"
description = "xlwings server for TL Sports Sales Inc."
readme = "README.md"
authors = [
    { name = "Liam", email = "95653151+lla1dlaw@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "intuit-oauth>=1.2.6",
    "python-quickbooks>=0.9.12",
    "xlwings-server>=1.11.0",
    "dataclasses>=0.8",
    "pretty-errors>=1.2.25",
    "python-decouple>=3.8",
    "rich>=15.0.0",
    "xlwings>=0.36.13",
    "watchfiles>=1.2.0",
]


[tool.xlwings_server]
manifest_id_dev = "4fcd1317-6a2f-4a9a-af5e-a6cd27492c5e"
manifest_id_qa = "2fb8e5f3-d057-4885-b647-686d658b9151"
manifest_id_uat = "35a6e2f1-4d6c-4608-9017-2e7f26d1b5d5"
manifest_id_staging = "277d361c-b8fc-4855-bcb7-3bee43f3cdc3"
manifest_id_prod = "836c5cfa-6ceb-4742-a99b-5161272f5b74"
